schema_version: 1

context:
  version: 3.2.0

package:
  name: file-read-backwards
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/file-read-backwards/file_read_backwards-${{version }}.tar.gz
  sha256: 5478d305ebaeaae8fe3c6585a24dfc3262170224450acc9321398f0d26cdd109

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check


requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - file_read_backwards
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/RobinNil/file_read_backwards
  repository: https://github.com/RobinNil/file_read_backwards
  documentation: hhttps://file-read-backwards.readthedocs.io/en/latest/index.html
  summary: Memory efficient way of reading files line-by-line from the end of file
  license: MIT
  license_file:
  - LICENSE

extra:
  recipe-maintainers:
    - apcamargo
